# Generated by Django 5.1.5 on 2025-01-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Nomi')),
                ('description', models.TextField(verbose_name="Ma'lumot")),
                ('image', models.ImageField(upload_to='services/')),
                ('link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Servis',
                'verbose_name_plural': 'Servislar',
                'db_table': 'Service',
                'managed': True,
            },
        ),
    ]
