# Generated by Django 5.1.5 on 2025-01-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicemodel',
            name='link',
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='image',
            field=models.ImageField(upload_to='services/', verbose_name='Rasmi'),
        ),
    ]
