# Generated by Django 5.0.7 on 2025-01-18 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0002_remove_servicemodel_link_alter_servicemodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategoriya nomi')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'db_table': 'Category',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='mebel.categorymodel', verbose_name='Kategoriya'),
            preserve_default=False,
        ),
    ]
