# Generated by Django 5.0.7 on 2025-01-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0003_categorymodel_servicemodel_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='testimonials/')),
                ('feedback', models.TextField()),
            ],
        ),
    ]
