# Generated by Django 5.0.7 on 2025-01-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0004_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FurnitureInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ismingiz')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Manzilingiz')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefon Raqamingiz')),
                ('furniture_type', models.CharField(choices=[('1', 'Yotoq Mebellari'), ('2', 'Oshxona Mebellari'), ('3', 'Ofis Mebellari'), ('4', 'Shkaflar'), ('5', 'Stullar va Jadvallar')], max_length=50, verbose_name='Mebel Turi')),
                ('message', models.TextField(blank=True, verbose_name='Maxsus Izohlaringiz')),
            ],
        ),
    ]
