# Generated by Django 5.0.7 on 2025-01-19 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0005_furnitureinquiry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FurnitureInquiry',
            new_name='ContactModel',
        ),
    ]
