# Generated by Django 5.0.7 on 2025-01-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0006_rename_furnitureinquiry_contactmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'managed': True, 'verbose_name': 'Aloqa', 'verbose_name_plural': 'Aloqalar'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'managed': True, 'verbose_name': 'Izoh', 'verbose_name_plural': 'Izohlar'},
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='client_name',
            field=models.CharField(max_length=100, verbose_name='Mijoz ismi'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='feedback',
            field=models.TextField(verbose_name='Fikr-mulohaza'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(upload_to='testimonials/', verbose_name='Rasmi'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='profession',
            field=models.CharField(max_length=100, verbose_name='Kasbi'),
        ),
        migrations.AlterModelTable(
            name='contactmodel',
            table='aloqa',
        ),
        migrations.AlterModelTable(
            name='testimonial',
            table='izoxlar',
        ),
    ]
