# Generated by Django 5.1.5 on 2025-01-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0007_alter_contactmodel_options_alter_testimonial_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMemberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('designation', models.CharField(max_length=100, verbose_name='Lavozim')),
                ('image', models.ImageField(upload_to='team/', verbose_name='Rasm')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='Facebook havola')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='Twitter havola')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='Instagram havola')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'db_table': 'Jamolar',
                'managed': True,
            },
        ),
    ]
