# Generated by Django 5.0.7 on 2025-01-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0008_teammembermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='teammembermodel',
            options={'managed': True, 'verbose_name': 'Team Member', 'verbose_name_plural': 'Bizning Jamolar'},
        ),
    ]
