# Generated by Django 5.0.7 on 2025-01-25 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0009_product_alter_teammembermodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
