# Generated by Django 5.0.7 on 2025-01-26 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0010_product_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'managed': True, 'verbose_name': 'Team Member', 'verbose_name_plural': 'Bizning Jamolar'},
        ),
        migrations.AlterModelTable(
            name='product',
            table='Maxsulot',
        ),
    ]
