# Generated by Django 5.0.7 on 2025-01-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0011_alter_product_options_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'managed': True, 'verbose_name': 'Team Member', 'verbose_name_plural': 'Bizning Maxsulaotlar'},
        ),
        migrations.AddField(
            model_name='testimonial',
            name='rating',
            field=models.PositiveIntegerField(default=0, verbose_name='Reyting (%)'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='profession',
            field=models.CharField(choices=[('oquvchi', "O'quvchi"), ('rasom', 'Rasom'), ('ishsiz', 'Ishsiz'), ('usta', 'Usta'), ('musiqa_ustozi', 'Musiqa ustozi')], max_length=100, verbose_name='Kasbi'),
        ),
    ]
