# Generated by Django 5.0.7 on 2025-01-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0012_alter_product_options_testimonial_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodel',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Chigirma'),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='is_discounted',
            field=models.BooleanField(default=False, verbose_name='Chigirma mavjudmi'),
        ),
    ]
