# Generated by Django 5.0.7 on 2025-01-26 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0013_servicemodel_discount_servicemodel_is_discounted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicemodel',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='servicemodel',
            name='is_discounted',
        ),
    ]
