# Generated by Django 5.0.7 on 2025-01-27 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0015_helprequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helprequest',
            name='user',
        ),
    ]
