# Generated by Django 5.0.7 on 2025-01-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0016_remove_helprequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='helprequest',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='helprequest',
            name='phone_number',
            field=models.CharField(default=2, max_length=15),
            preserve_default=False,
        ),
    ]
