# Generated by Django 5.0.7 on 2025-02-01 05:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0017_helprequest_email_helprequest_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelpRequest',
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'managed': True, 'ordering': ['-rating'], 'verbose_name': 'Izoh', 'verbose_name_plural': 'Izohlar'},
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='profession',
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(default='testimonials/default.jpg', upload_to='testimonials/', verbose_name='Rasmi'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Reyting (%)'),
        ),
    ]
